<?php

/**
 * @file
 * Contains repeat_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function repeat_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the repeat_ui module.
    case 'help.page.repeat_ui':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UI for REPEAT') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function repeat_ui_theme() {
  return [
    'repeat_ui' => [
      'render element' => 'children',
    ],
  ];
}
